### ISSUE TITLE
京东通天塔签到失败

### ISSUE THREAD

**Issue by sxdxzkq** [inoyna12/JDsc#1]
## 开始执行... 2022-03-21 00:03:08

🔔京东通天塔--签到, 开始!

====================共1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/3/21 00:03:08=====================

【风之凌殇】 友情提示：当前未设置 ShareCodeConfigName 或 ShareCodeEnvName 环境变量，将不会尝试在nodejs中生成互助码的环境变量。ps: 两个值目前分别为 undefined undefined

******开始【京东账号1】*********

签到开始........
失败：00017_jingbean incomeBeans threshold error!
TypeError: Cannot read properties of null (reading '1')
    at /ql/scripts/inoyna12_JDsc/jd_m_sign.js:115:81
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/inoyna12_JDsc/jd_m_sign.js:251:5721)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

## 执行结束... 2022-03-21 00:03:10 耗时 2 秒

**Comment by inoyna12** [comment]
别急，我这两天才更新，所有脚本都会更新一遍的

**Comment by sxdxzkq** [comment]
感谢大佬

**Comment by sxdxzkq** [comment]
🔔推推赚大钱, 开始!

====================共1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/3/23 09:06:35=====================

【风之凌殇】 友情提示：当前未设置 ShareCodeConfigName 或 ShareCodeEnvName 环境变量，将不会尝试在nodejs中生成互助码的环境变量。ps: 两个值目前分别为 undefined undefined

开始【京东账号1】
开启活动
:开启红包msg:重复发起活动,code:701
邀请码:


开始【京东账号1】
推推助力
"connect ECONNREFUSED 0.0.0.0:443"
推推赚大钱 API请求失败，请检查网路重试

🔔推推赚大钱, 结束! 🕛 7.192 秒

/ql/scripts/inoyna12_JDsc/jd_tuitui1.js:65
        for (let j = 0; j < $.authorCode.length; j++) {
                                         ^

TypeError: Cannot read properties of undefined (reading 'length')
    at /ql/scripts/inoyna12_JDsc/jd_tuitui1.js:65:42
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Node.js v17.5.0

## 执行结束... 2022-03-23 09:06:42 耗时 8 秒

**Comment by sxdxzkq** [comment]
## 开始执行... 2022-03-23 18:00:00


====================共1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2022/3/23 18:00:01=====================

【风之凌殇】 友情提示：当前未设置 ShareCodeConfigName 或 ShareCodeEnvName 环境变量，将不会尝试在nodejs中生成互助码的环境变量。ps: 两个值目前分别为 undefined undefined
2022-03-23 18:00:01.111  环境变量添加 PEARL_MONEY 设置兑换金额，不填默认5元
2022-03-23 18:00:01.116 M财富岛珍珠兑换 /ql/scripts/inoyna12_JDsc/jx_cfd_pearl_exchange1.js 开始运行...
TypeError: Cannot read properties of undefined (reading 'length')
    at Env.$.logic (/ql/scripts/inoyna12_JDsc/jx_cfd_pearl_exchange1.js:18:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Env.run (/ql/scripts/inoyna12_JDsc/utils/magic.js:169:21)
2022-03-23 18:00:01.426 M财富岛珍珠兑换 运行结束,耗时 309ms


## 执行结束... 2022-03-23 18:00:01 耗时 1 秒
